### ISSUE TITLE
shadowsocksr源码404

### ISSUE THREAD

**Issue by ncc0706** [s0fx2/shadowsocks-rss-alpine#1]
https://github.com/shadowsocksr/shadowsocksr.git

**Comment by s0fx2** [comment]
BreakWa11关闭了代码库，更新到其他人接手后的代码库，默认使用ShadowsocksR作为服务器

**Comment by ncc0706** [comment]
@s0fx2 代码库地址呢

**Comment by ncc0706** [comment]
@s0fx2 看到了
